local:
  CLUSTER:
    HOST: 'https://E203283227F6D91EA3CD8E07B9406FBC.yl4.ap-northeast-2.eks.amazonaws.com:6443'
    KUBE_CONFIG_PATH: 'D:\PycharmProjects\MLOps-API\certs\kubeconfig'
    VOLUME_NFS_SERVER: 'E203283227F6D91EA3CD8E07B9406FBC.yl4.ap-northeast-2.eks.amazonaws.com'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://a8580289d049e4af8b91a26458a53c55-1063763824.ap-northeast-2.elb.amazonaws.com:8888'
  MINIO:
    ENDPOINT: 'http://a966724d776b642698b266680d8596be-786556784.ap-northeast-2.elb.amazonaws.com:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://a09372fc6e31b45f6a1010205f9af2fc-583432073.ap-northeast-2.elb.amazonaws.com:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"

container:
  CLUSTER:
    HOST: 'https://E203283227F6D91EA3CD8E07B9406FBC.yl4.ap-northeast-2.eks.amazonaws.com:6443'
    KUBE_CONFIG_PATH: '/home/wisenut/app/certs/kubeconfig'
    VOLUME_NFS_SERVER: 'E203283227F6D91EA3CD8E07B9406FBC.yl4.ap-northeast-2.eks.amazonaws.com'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://ml-pipeline.kubeflow.svc.cluster.local:8888'
  MINIO:
    ENDPOINT: 'http://minio-service.kubeflow.svc.cluster.local:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://custom-mlflow-service.mlflow-system.svc.cluster.local:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"