local:
  CLUSTER:
    HOST: 'https://a80fe9e6b06c24bee94be3af2d93c22e-1779732805.ap-northeast-2.elb.amazonaws.com'
    KUBE_CONFIG_PATH: 'D:\PycharmProjects\MLOps-API\certs\kubeconfig'
    VOLUME_NFS_SERVER: '1B3DEBEBA1D6063A068132F4E339F80C.yl4.ap-northeast-2.eks.amazonaws.com'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://a8e559c417474471192fda467f27528f-808188920.ap-northeast-2.elb.amazonaws.com:8888'
  MINIO:
    ENDPOINT: 'http://ae838404cb4e94d38bd3c4986bde5b4c-2058643848.ap-northeast-2.elb.amazonaws.com:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://a6bcaa9aed8e54b38ae33d2b81378645-1569294732.ap-northeast-2.elb.amazonaws.com:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"

container:
  CLUSTER:
    HOST: ''
    KUBE_CONFIG_PATH: '/home/wisenut/app/certs/config'
    VOLUME_NFS_SERVER: ''
    VOLUME_NFS_PATH: ''
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://ml-pipeline.kubeflow.svc.cluster.local:8888'
  MINIO:
    ENDPOINT: 'http://minio-service.kubeflow.svc.cluster.local:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://custom-mlflow-service.mlflow-system.svc.cluster.local:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"