local:
  CLUSTER:
    HOST: 'https://211.39.140.43:30443'
    KUBE_CONFIG_PATH: 'D:\repoPy\MLOps-API\certs\kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://211.39.140.43:31294'
  MINIO:
    ENDPOINT: 'http://211.39.140.30:8082'
    ACCESS_KEY: 'HoItKC9L7DkLjenn'
    SECRET_KEY: 'hVQN7JZWrtSvdpfST5Jxv9uXPVmHtGjK'
  MLFLOW:
    TRACKING_URI: 'http://a66416857e07d4ad692b074494b68a36-2044209649.ap-northeast-2.elb.amazonaws.com:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"

container:
  CLUSTER:
    HOST: 'https://211.39.140.43:30443'
    KUBE_CONFIG_PATH: '/home/wisenut/app/certs/kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    PIPELINES:
      ENDPOINT: 'http://ml-pipeline.kubeflow.svc.cluster.local:8888'
  MINIO:
    ENDPOINT: 'http://minio-service.kubeflow.svc.cluster.local:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://mlflow-server-service.mlflow-system.svc.cluster.local:5000'
  DATABASE:
    SQLALCHEMY_DATABASE_URL: "sqlite:///./sql_app.db"