local:
  CLUSTER:
    HOST: 'https://211.39.140.43:32443'
    CA_CERT_PATH: 'D:\repoPy\MLOps-API\certs\k8s-ca.cert'
    KUBE_CONFIG_PATH: 'D:\repoPy\MLOps-API\certs\kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  KUBEFLOW:
    USERNAME: 'user@example.com'
    PASSWORD: '12341234'
  MINIO:
    ENDPOINT: 'http://211.39.140.30:8082'
    ACCESS_KEY: 'HoItKC9L7DkLjenn'
    SECRET_KEY: 'hVQN7JZWrtSvdpfST5Jxv9uXPVmHtGjK'
  MLFLOW:
    TRACKING_URI: 'http://localhost:5000'

container:
  CLUSTER:
    HOST: 'https://211.39.140.43:32443'
    CA_CERT: '/home/wisenut/app/certs/k8s-ca.cert'
    KUBE_CONFIG_PATH: '/home/wisenut/app/certs/kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  MINIO:
    ENDPOINT: 'http://minio-service.kubeflow.svc.cluster.local:9000'
    ACCESS_KEY: 'minio'
    SECRET_KEY: 'minio123'
  MLFLOW:
    TRACKING_URI: 'http://mlflow-server-service.mlflow-system.svc.cluster.local:5000'