local:
  CLUSTER:
    HOST: 'https://211.39.140.43:6443'
    KUBE_CONFIG_PATH: 'D:\repoPy\MLOps-API\certs\kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  MINIO:
    ENDPOINT: 'http://211.39.140.30:8082'
    ACCESS_KEY: 'HoItKC9L7DkLjenn'
    SECRET_KEY: 'hVQN7JZWrtSvdpfST5Jxv9uXPVmHtGjK'

container:
  CLUSTER:
    HOST: 'https://211.39.140.43:6443'
    KUBE_CONFIG_PATH: '/home/wisenut/app/certs/kubeconfig'
    VOLUME_NFS_SERVER: '211.39.140.43'
    VOLUME_NFS_PATH: '/home/wisenut/nfs4share'
  MINIO:
    ENDPOINT: 'http://211.39.140.30:8082'
    ACCESS_KEY: 'HoItKC9L7DkLjenn'
    SECRET_KEY: 'hVQN7JZWrtSvdpfST5Jxv9uXPVmHtGjK'