[build-system]
requires = [
    "setuptools >= 61.0.0",
    "wheel >= 0.37.1"
]
build-backend = "setuptools.build_meta"

[project]
requires-python = "3.9"

[tool.flake8]
ignore = "W"
max-line-length = 125
max-complexity = 10
exclude = ".git,__pycache__,docs,venv,tests,build,dist"