from src import app_config

MLFLOW_S3_ENDPOINT_URL = app_config.MINIO_ENDPOINT
AWS_ACCESS_KEY_ID = app_config.MINIO_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = app_config.MINIO_SECRET_KEY
MLFLOW_TRACKING_URI = app_config.MLFLOW_TRACKING_URI
